import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    // Home page
    'home.badge': 'The Complete MLBB Learning Platform',
    'home.title.1': 'Master the ',
    'home.title.2': 'Land of Dawn',
    'home.subtitle': 'From your very first match to reaching Mythical Glory — your complete, structured guide to Mobile Legends: Bang Bang.',
    'home.cta.start': 'Start Learning →',
    'home.cta.heroes': 'Browse Hero Guides',
    'home.stat.heroes': 'Hero Guides',
    'home.stat.sections': 'Course Sections',
    'home.stat.creators': 'Pro Creators',
    'home.stat.free': 'Forever',
    'home.where': 'Where Do You Want to ',
    'home.where.span': 'Begin?',
    'home.where.sub': 'Six structured modules covering everything from basics to professional-level strategies.',
    'home.why': 'Why Use ',
    'home.why.span': 'MLBB Academy?',
    'home.why.sub': 'Everything you need to improve, in one place — no fluff, just results.',
    'home.track': 'Track Your ',
    'home.track.span': 'Progress',
    'home.track.sub': 'Mark sections as complete — your progress is saved locally in your browser.',
    'home.tips': 'Quick ',
    'home.tips.span': 'Tips',
    'home.tips.sub': 'Fast, actionable tips to instantly improve your gameplay.',
    'home.tips.cta': 'View All Strategies →',
    'home.cta.title.1': 'Ready to Reach ',
    'home.cta.title.2': 'Mythical Glory?',
    'home.cta.sub': 'Start with the basics and work your way up. Your journey begins here.',
    'home.cta.begin': 'Begin Your Journey →',
    'home.cta.lingo': 'Learn the Lingo',

    // Home - Quick Nav Cards
    'home.card.gs.title': 'Getting Started',
    'home.card.gs.desc': 'New to MLBB? Learn the basics, game modes, controls, and beginner tips to hit the ground running.',
    'home.card.gs.badge': 'Beginner',
    'home.card.gm.title': 'Game Mechanics',
    'home.card.gm.desc': 'Master the map, gold & EXP system, all 6 roles, emblems, battle spells, and item builds.',
    'home.card.gm.badge': 'Core',
    'home.card.hg.title': 'Hero Guides',
    'home.card.hg.desc': 'Browse 30+ heroes with role, difficulty, recommended spells, and essential gameplay tips.',
    'home.card.hg.badge': 'Essential',
    'home.card.int.title': 'Intermediate',
    'home.card.int.desc': 'Improve your farming, map awareness, rotation, and objective control to climb the ranked ladder.',
    'home.card.int.badge': 'Intermediate',
    'home.card.adv.title': 'Advanced',
    'home.card.adv.desc': 'Advanced macro & micro strategies, counter-jungling, ranked climbing, and mental game.',
    'home.card.adv.badge': 'Advanced',
    'home.card.pro.title': 'Pro Resources',
    'home.card.pro.desc': 'Top content creators, official MPL esports channels, and world championship resources.',
    'home.card.pro.badge': 'Pro',

    // Home - Benefits
    'home.benefit.structured.title': 'Structured Learning',
    'home.benefit.structured.desc': 'Organized from absolute beginner to advanced strategies. Follow the path or jump to what you need.',
    'home.benefit.hero.title': 'Hero-Specific Tips',
    'home.benefit.hero.desc': 'Detailed guides for 30+ heroes across all 6 roles with difficulty ratings and key combos.',
    'home.benefit.updated.title': 'Always Updated',
    'home.benefit.updated.desc': 'Reflects current meta strategies and the most relevant content creators in the MLBB community.',

    // Home - Tips
    'home.tip.awareness': 'Always check the minimap every 3–5 seconds — map awareness wins games.',
    'home.tip.objectives': 'Prioritize Turtle in the early game (before 4 min) for a big gold advantage.',
    'home.tip.rotation': 'Your tank should always rotate to pushed lanes to prevent turret loss.',
    'home.tip.farming': 'Last-hitting creeps gives you more gold — aim for every last hit in lane.',

    // Footer
    'footer.tagline': 'Your complete guide from Beginner to Mythical Glory. Master the Land of Dawn.',
    'footer.disclaimer': '⚠️ This is a fan-made educational resource. Not affiliated with Moonton or Mobile Legends: Bang Bang.',

    // Getting Started
    'gs.tag': '🎮 Beginner',
    'gs.title.1': 'Getting ',
    'gs.title.2': 'Started',
    'gs.subtitle': 'Everything you need to know to download, set up, and play your first matches in Mobile Legends: Bang Bang.',
    'gs.what.title.1': 'What is ',
    'gs.what.title.2': 'Mobile Legends: Bang Bang?',
    'gs.what.p1': 'Mobile Legends: Bang Bang (MLBB) is a 5v5 multiplayer online battle arena (MOBA) game developed by Moonton. Released in 2016, it has grown into one of the most popular mobile games in Southeast Asia and worldwide, with millions of daily players.',
    'gs.what.p2': 'Two teams of 5 players each compete to destroy the enemy\'s base (the Nexus). The map has three main lanes — Top, Mid, and Bottom — connected by a jungle. Each player controls a unique hero with special abilities.',
    'gs.what.p3': 'Matches typically last 15–25 minutes, making MLBB perfect for mobile play sessions.',
    'gs.facts.title': '⚡ Quick Facts',
    'gs.download.title.1': 'Download & ',
    'gs.download.title.2': 'Setup',
    'gs.ui.title.1': 'In-Game ',
    'gs.ui.title.2': 'UI Overview',
    'gs.modes.title.1': 'Game ',
    'gs.modes.title.2': 'Modes',
    'gs.modes.subtitle': 'MLBB offers multiple modes to suit every play style and mood.',
    'gs.tips.title.1': 'Beginner ',
    'gs.tips.title.2': 'Tips',
    'gs.mistakes.title.1': 'Common ',
    'gs.mistakes.title.2': 'Mistakes & Fixes',
    'gs.mistakes.header.mistake': '❌ Common Mistake',
    'gs.mistakes.header.fix': '✅ The Fix',
    'gs.quiz.title': '🧠 Knowledge Check',

    // Getting Started - Game Modes
    'gs.mode.classic.name': 'Classic',
    'gs.mode.classic.desc': 'Standard 5v5 match. Best for practicing heroes and strategies without rank pressure. Great for beginners.',
    'gs.mode.ranked.name': 'Ranked',
    'gs.mode.ranked.desc': 'Competitive mode where you earn rank points. Play here once you understand your preferred role and a few heroes.',
    'gs.mode.brawl.name': 'Brawl',
    'gs.mode.brawl.desc': 'Chaotic single-lane random hero mode. Fast matches. Good for understanding hero abilities quickly.',
    'gs.mode.custom.name': 'Custom',
    'gs.mode.custom.desc': 'Create private rooms to practice with friends or specific scenarios. Useful for testing combos.',
    'gs.mode.arcade.name': 'Arcade',
    'gs.mode.arcade.desc': 'Rotating fun mini-game modes. Perfect for a break from serious play. New modes regularly added.',
    'gs.mode.ai.name': 'vs. AI',
    'gs.mode.ai.desc': 'Fight against bots. Ideal when first learning a new hero or warming up before a ranked session.',

    // Getting Started - Beginner Tips
    'gs.tip.1': 'Start with easy-difficulty heroes like Miya, Freya, or Rafaela.',
    'gs.tip.2': 'Check the minimap every few seconds — map awareness is crucial.',
    'gs.tip.3': 'Stay with teammates early game; avoid going alone in enemy territory.',
    'gs.tip.4': 'Use your battle spell (like Flicker) wisely — it has a long cooldown.',
    'gs.tip.5': 'Don\'t sell items to buy others — upgrade them as the game progresses.',
    'gs.tip.6': 'Mute toxic players immediately. Mental focus wins games.',
    'gs.tip.7': 'Read item descriptions to understand what you\'re buying.',
    'gs.tip.8': 'Play both Classic and vs. AI before entering ranked matches.',

    // Getting Started - Mistakes
    'gs.mistake.1.mistake': 'Overextending alone',
    'gs.mistake.1.fix': 'Always check the minimap before pushing deep into enemy territory.',
    'gs.mistake.2.mistake': 'Buying random items',
    'gs.mistake.2.fix': 'Follow recommended builds or guides for your hero\'s role.',
    'gs.mistake.3.mistake': 'Ignoring objectives',
    'gs.mistake.3.fix': 'Always contest Turtle (early game) and Lord (late game).',
    'gs.mistake.4.mistake': 'Never rotating',
    'gs.mistake.4.fix': 'Help teammates in other lanes when your lane is safe.',
    'gs.mistake.5.mistake': 'Staying in base too long',
    'gs.mistake.5.fix': 'Return to lane or rotate as soon as you\'ve spent your gold.',

    // Getting Started - Download Steps
    'gs.step.1.title': 'Download the App',
    'gs.step.1.desc': 'Search "Mobile Legends: Bang Bang" on the App Store (iOS) or Google Play Store (Android). The download is free.',
    'gs.step.2.title': 'Create an Account',
    'gs.step.2.desc': 'Log in with Facebook, Google, Moonton, or VK. Using Facebook/Google links your account across devices safely.',
    'gs.step.3.title': 'Complete the Tutorial',
    'gs.step.3.desc': 'MLBB has a built-in tutorial. Complete it fully — it teaches movement, skills, attacking, and objectives.',
    'gs.step.4.title': 'Adjust Settings',
    'gs.step.4.desc': 'Go to Settings → Controls. Enable "Smart Targeting" early on. Adjust skill button size and layout to your comfort.',
    'gs.step.5.title': 'Try Free Heroes',
    'gs.step.5.desc': 'MLBB provides free rotating heroes each week. Experiment with them to discover your preferred role.',
    'gs.step.6.title': 'Play vs. AI First',
    'gs.step.6.desc': 'Play a few Bot matches before jumping into Classic or Ranked. Get comfortable with your hero first.',

    // Getting Started - UI Overview
    'gs.ui.minimap.label': 'Minimap',
    'gs.ui.minimap.desc': 'Shows real-time positions of all visible heroes. Check it every 3–5 seconds.',
    'gs.ui.timer.label': 'Timer & Score',
    'gs.ui.timer.desc': 'Game clock, kill score, and gold advantage display.',
    'gs.ui.gold.label': 'Gold Counter',
    'gs.ui.gold.desc': 'Your current gold. Tells you how close you are to your next item.',
    'gs.ui.joystick.label': 'Movement Joystick',
    'gs.ui.joystick.desc': 'Drag to move your hero. Tap briefly to stop and auto-attack nearest enemy.',
    'gs.ui.skills.label': 'Skill Buttons',
    'gs.ui.skills.desc': 'Your hero\'s 3 skills plus basic attack. Skill 2 is usually your key ability.',
    'gs.ui.spell.label': 'Battle Spell',
    'gs.ui.spell.desc': 'Special ability (Flicker, Retribution, etc.) chosen before the match.',

    // Getting Started - Quiz
    'gs.quiz.q1': 'Which game mode is best for beginners to learn without rank pressure?',
    'gs.quiz.q1.a': 'Ranked',
    'gs.quiz.q1.b': 'Classic',
    'gs.quiz.q1.c': 'Brawl',
    'gs.quiz.q1.d': 'vs. AI',
    'gs.quiz.q1.explain': 'Classic mode is the standard 5v5 match without rank stakes — perfect for practice.',
    'gs.quiz.q2': 'What is the most important map habit to develop as a beginner?',
    'gs.quiz.q2.a': 'Always pushing turrets',
    'gs.quiz.q2.b': 'Checking the minimap regularly',
    'gs.quiz.q2.c': 'Buying expensive items first',
    'gs.quiz.q2.d': 'Fighting under enemy turret',
    'gs.quiz.q2.explain': 'Map awareness via the minimap is the single most impactful habit to build early.',
    'gs.quiz.q3': 'Which of these is NOT a standard role in MLBB?',
    'gs.quiz.q3.a': 'Marksman',
    'gs.quiz.q3.b': 'Support',
    'gs.quiz.q3.c': 'Healer',
    'gs.quiz.q3.d': 'Assassin',
    'gs.quiz.q3.explain': 'The 6 roles are: Tank, Fighter, Assassin, Mage, Marksman, and Support. There is no dedicated "Healer" role.',

    // Game Mechanics
    'gm.tag': '⚙️ Core',
    'gm.title.1': 'Game ',
    'gm.title.2': 'Mechanics',
    'gm.subtitle': 'Master the map, economy, roles, emblems, and spells to build a strong foundation for every match.',
    'gm.map.title.1': 'The Map: ',
    'gm.map.title.2': 'Land of Dawn',
    'gm.map.desc': 'The battle takes place on a symmetrical map called the Land of Dawn. It is divided into two halves — blue side (your team) and red side (enemies). Three lanes connect the bases, with a jungle in between.',
    'gm.obj.title': '🎯 Key Objectives',
    'gm.gold.title.1': 'Gold & ',
    'gm.gold.title.2': 'EXP System',
    'gm.roles.title.1': 'Hero ',
    'gm.roles.title.2': 'Roles',
    'gm.roles.subtitle': 'Understanding roles is fundamental. Each team needs a balanced composition to succeed.',
    'gm.emblems.title.1': 'Emblem ',
    'gm.emblems.title.2': 'System',
    'gm.emblems.subtitle': 'Emblems provide stat bonuses and talent perks. Always equip the emblem matching your hero\'s role.',
    'gm.spells.title.1': 'Battle ',
    'gm.spells.title.2': 'Spells',
    'gm.spells.subtitle': 'Battle Spells are powerful abilities chosen before each match. Picking the right spell for your hero is critical.',
    'gm.items.title.1': 'Items & ',
    'gm.items.title.2': 'Builds',
    'gm.items.subtitle': 'Items are bought with gold during the match and dramatically increase your hero\'s power.',
    'gm.difficulty': ' Difficulty',
    'gm.duties': '🎯 Core Duties',
    'gm.heroes': '🦸 Example Heroes',
    'gm.spell': '⚡ Recommended Spell',
    'gm.bestfor': 'Best for:',

    // Hero Guides
    'hg.tag': '🦸 Heroes',
    'hg.title.1': 'Hero ',
    'hg.title.2': 'Guides',
    'hg.subtitle': 'Browse guides for 30 heroes across all 6 roles. Filter by role to find your main.',
    'hg.shown': ' shown',
    'hg.hero': ' hero',
    'hg.heroes': ' heroes',
    'hg.tips': '💡 Key Tips',
    'hg.weak': '🔄 Weak vs:',
    'hg.less': '▲ Less',
    'hg.more': '▼ Tips',
    'hg.tier.title.1': 'Current ',
    'hg.tier.title.2': 'Meta Tier List',
    'hg.tier.subtitle': 'General tier guide for ranked play. Meta shifts each patch — always check recent patch notes.',
    'hg.synergy.title.1': 'Synergy & ',
    'hg.synergy.title.2': 'Counter Tips',
    'hg.synergy.strong': '✅ Strong Synergies',
    'hg.synergy.counter': '❌ Common Counters',

    // Intermediate
    'int.tag': '📈 Intermediate',
    'int.title.1': 'Intermediate ',
    'int.title.2': 'Strategies',
    'int.subtitle': 'Bridge the gap from casual player to consistent ranked performer with these core intermediate concepts.',
    'int.farming.title.1': 'Last Hitting & ',
    'int.farming.title.2': 'Farming',
    'int.farming.desc': 'Last hitting means landing the killing blow on a lane minion to secure the full gold reward. Missing last hits — even by 1 attack — means lost gold that compounds over the game.',
    'int.farming.stats': '📊 Farming Goals',
    'int.map.title.1': 'Map Awareness & ',
    'int.map.title.2': 'Minimap',
    'int.rotation.title.1': 'Rotation ',
    'int.rotation.title.2': 'Strategies',
    'int.obj.title.1': 'Objective ',
    'int.obj.title.2': 'Prioritization',
    'int.comp.title.1': 'Team ',
    'int.comp.title.2': 'Composition',
    'int.comp.subtitle': 'A balanced team composition is critical for success. At the draft/selection screen, build a team with multiple roles covered.',
    'int.engage.title.1': 'Engage vs ',
    'int.engage.title.2': 'Disengage',
    'int.engage.when': '⚔️ When to Engage',
    'int.disengage.when': '🛡️ When to Disengage',
    'int.quiz.title': '🧠 Intermediate Knowledge Check',

    // Advanced
    'adv.tag': '🏆 Advanced',
    'adv.title.1': 'Advanced ',
    'adv.title.2': 'Strategies',
    'adv.subtitle': 'Elite-level macro and micro techniques for players aiming for Mythical Glory and beyond.',
    'adv.macro.title.1': 'Advanced ',
    'adv.macro.title.2': 'Macro Play',
    'adv.macro.subtitle': 'Macro refers to large-scale game decisions — map movement, objectives, and pressure.',
    'adv.micro.title.1': 'Advanced ',
    'adv.micro.title.2': 'Micro Techniques',
    'adv.micro.subtitle': 'Micro refers to individual mechanical skill — how precisely you control your hero in fights.',
    'adv.micro.practice': '🎮 Practice:',
    'adv.cj.title.1': 'Counter ',
    'adv.cj.title.2': 'Jungling',
    'adv.cj.desc': 'Counter-jungling means invading the enemy jungle to steal their camps, deny their gold/EXP, and create an early advantage. It is high risk, high reward.',
    'adv.cj.timers': '⏰ Key Jungle Timers',
    'adv.rank.title.1': 'Ranked Climbing ',
    'adv.rank.title.2': 'Guide',
    'adv.rank.subtitle': 'Every rank tier requires different focus areas. Here\'s what matters most at each stage.',
    'adv.mental.title.1': 'Mental Game & ',
    'adv.mental.title.2': 'Tilt Management',
    'adv.patch.title.1': 'Meta & ',
    'adv.patch.title.2': 'Patch Analysis',
    'adv.patch.desc': 'MLBB releases patches every 2–4 weeks. Each patch can dramatically shift the meta. Adapting to patches separates stagnant players from climbers.',

    // Pro Resources
    'pro.tag': '⭐ Pro Level',
    'pro.title.1': 'Pro ',
    'pro.title.2': 'Resources',
    'pro.subtitle': 'The best content creators, official esports channels, and professional resources to accelerate your MLBB journey.',
    'pro.creators.title.1': 'Top Content ',
    'pro.creators.title.2': 'Creators',
    'pro.creators.subtitle': 'These creators provide the best educational and entertainment content in the MLBB community.',
    'pro.visit': 'Visit Channel →',
    'pro.mpl.title.1': 'Official MPL ',
    'pro.mpl.title.2': 'Esports Leagues',
    'pro.mpl.subtitle': 'The Mobile Legends Professional League (MPL) is the premier competitive circuit. Watch to learn from the best players in the world.',
    'pro.mpl.watch': 'Watch →',
    'pro.mseries.title.1': 'M-Series ',
    'pro.mseries.title.2': 'World Championship',
    'pro.mseries.desc': 'The M-Series is MLBB\'s annual World Championship where the best MPL teams from all regions compete for the title of World Champion. It is the grandest stage in mobile MOBA esports.',
    'pro.mseries.champions': '🏆 Past Champions',
    'pro.why.title.1': 'Why Watch ',
    'pro.why.title.2': 'Pro Play?',

    // Patch Notes
    'patch.tag': '📋 Patch Updates',
    'patch.title.1': 'Patch ',
    'patch.title.2': 'Notes',
    'patch.subtitle': 'Stay updated with the latest MLBB patches. Learn where to find patch notes, how to analyze changes, and adapt your gameplay to every update.',
    'patch.where.title.1': 'Where to Find ',
    'patch.where.title.2': 'Patch Notes',
    'patch.where.subtitle': 'Multiple sources to stay informed about every MLBB update.',
    'patch.visit': 'Visit Source →',
    'patch.analyze.title.1': 'How to Analyze ',
    'patch.analyze.title.2': 'a New Patch',
    'patch.analyze.subtitle': 'Follow this checklist every time a new patch drops to stay ahead of the meta.',
    'patch.terms.title.1': 'Patch ',
    'patch.terms.title.2': 'Terminology',
    'patch.terms.subtitle': 'Common terms you will see in patch notes and what they mean.',
    'patch.cycle.title.1': 'MLBB Patch ',
    'patch.cycle.title.2': 'Cycle',
    'patch.cycle.desc': 'MLBB typically releases patches every 2–4 weeks. Major patches include hero adjustments, new heroes, item changes, and sometimes map modifications. Understanding the patch cycle helps you prepare and adapt faster than your opponents.',
    'patch.cycle.tips.title': '💡 Pro Tips for Patch Day',

    // Glossary
    'glossary.tag': '📖 Reference',
    'glossary.title.1': 'MLBB ',
    'glossary.title.2': 'Glossary',
    'glossary.subtitle': 'A complete reference of MLBB terminology, abbreviations, and concepts. Search any term to find its meaning.',
    'glossary.search.placeholder': 'Search terms, abbreviations, or descriptions...',
    'glossary.total': 'total',
    'glossary.matching': 'matching',
    'glossary.empty': 'No terms found matching',

    // About
    'about.tag': 'ℹ️ About',
    'about.title.1': 'About ',
    'about.title.2': 'MLBB Academy',
    'about.subtitle': 'A fan-made educational resource dedicated to helping players of all skill levels master Mobile Legends: Bang Bang.',
    'about.mission.title.1': 'Our ',
    'about.mission.title.2': 'Mission',
    'about.mission.p1': 'MLBB Academy was created to be the most comprehensive, free, and accessible learning resource for Mobile Legends: Bang Bang players worldwide.',
    'about.mission.p2': 'Whether you just downloaded the game or you\'re pushing toward Mythical Glory, this site provides structured guides, hero-specific tips, and curated pro resources to help you improve at every stage of your journey.',
    'about.mission.p3': 'We believe great MLBB resources should be free, well-organized, and genuinely helpful — no pay-walls, no fluff, just practical knowledge you can apply in your next match.',
    'about.stats.title': '📊 Site Overview',
    'about.disclaimer.title': 'Important Disclaimer',
    'about.disclaimer.p1': 'MLBB Academy is a fan-made, unofficial educational resource. This website is not affiliated with, endorsed by, or connected to Moonton or Mobile Legends: Bang Bang in any official capacity.',
    'about.disclaimer.p2': 'All game-related content, including hero names, abilities, items, and game mechanics, are the intellectual property of Moonton. This website exists purely for educational and community purposes.',
    'about.disclaimer.p3': 'Hero data, meta information, and strategies may become outdated as the game receives regular patches and updates. Always verify current meta information with up-to-date patch notes.',
    'about.disclaimer.p4': 'Links to external content creators and websites are provided for informational purposes. We are not responsible for content on external sites.',
    'about.credits.title.1': 'Community ',
    'about.credits.title.2': 'Credits',
    'about.credits.subtitle': 'This site\'s strategy content was influenced by the incredible MLBB community and its dedicated content creators. A special thanks to:',
    'about.credits.note': 'These creators have contributed immensely to the MLBB community through educational content, guides, and entertainment. Visit the {link} page to find their channels.',
    'about.credits.link': 'Pro Resources',
    'about.howto.title.1': 'How to Use ',
    'about.howto.title.2': 'This Guide',
    'about.contribute.title': '🤝 Want to Contribute?',
    'about.contribute.desc': 'MLBB Academy thrives on community knowledge. If you have suggestions, corrections, or additional content ideas:',
    'about.contribute.note': 'This is a community resource — your feedback makes it better for everyone.',

    // About - How to Use
    'about.howto.1.title': 'Complete Beginners',
    'about.howto.1.desc': 'Start with Getting Started → Game Mechanics → Hero Guides. Master one hero before expanding your pool.',
    'about.howto.1.cta': 'Begin Here',
    'about.howto.2.title': 'Casual to Ranked',
    'about.howto.2.desc': 'Read Intermediate strategies. Focus on map awareness, farming, and rotation before pushing ranked.',
    'about.howto.2.cta': 'Level Up',
    'about.howto.3.title': 'Pushing to Mythic',
    'about.howto.3.desc': 'Study Advanced macro/micro, counter-jungling, and the mental game section.',
    'about.howto.3.cta': 'Go Advanced',
    'about.howto.4.title': 'Learn the Language',
    'about.howto.4.desc': 'Use the Glossary any time you encounter an unfamiliar term or abbreviation.',
    'about.howto.4.cta': 'Open Glossary',

    // About - Stats
    'about.stat.sections': 'Course Sections',
    'about.stat.heroes': 'Hero Guides',
    'about.stat.glossary': 'Glossary Terms',
    'about.stat.creators': 'Featured Creators',
    'about.stat.mpl': 'MPL Regions Covered',
    'about.stat.cost': 'Cost to Use',
    'about.stat.cost.value': 'Free Forever',

    // About - Contribute list
    'about.contribute.1': '📧 Spotted an error? We\'d love to know so we can fix it.',
    'about.contribute.2': '🦸 Want a specific hero guide added or expanded? Let us know.',
    'about.contribute.3': '💡 Have a strategy tip that\'s not here? Share your knowledge.',
    'about.contribute.4': '📹 Know a great creator we should feature? Recommend them.',
  },
  tl: {
    // Home page
    'home.badge': 'Ang Kumpletong MLBB Learning Platform',
    'home.title.1': 'Maging Master sa ',
    'home.title.2': 'Land of Dawn',
    'home.subtitle': 'Mula sa iyong unang laro hanggang sa maabot ang Mythical Glory — ang kumpletong gabay mo sa Mobile Legends: Bang Bang.',
    'home.cta.start': 'Magsimula →',
    'home.cta.heroes': 'Tingnan ang Mga Bayani',
    'home.stat.heroes': 'Gabay sa Bayani',
    'home.stat.sections': 'Mga Seksyon',
    'home.stat.creators': 'Pro Creators',
    'home.stat.free': 'Magpakailanman',
    'home.where': 'Saan Mo Gustong ',
    'home.where.span': 'Magsimula?',
    'home.where.sub': 'Anim na structured na module mula sa basics hanggang sa professional-level na mga stratehiya.',
    'home.why': 'Bakit Gamitin ang ',
    'home.why.span': 'MLBB Academy?',
    'home.why.sub': 'Lahat ng kailangan mo para gumaling, sa isang lugar — walang kalokohan, puro resulta.',
    'home.track': 'Subaybayan ang Iyong ',
    'home.track.span': 'Progreso',
    'home.track.sub': 'Markahan ang mga seksyon bilang kumpleto — nai-save ang progreso mo sa iyong browser.',
    'home.tips': 'Mga Mabilisang ',
    'home.tips.span': 'Tips',
    'home.tips.sub': 'Mabilis at praktikal na mga tip para agad mapahusay ang iyong laro.',
    'home.tips.cta': 'Tingnan Lahat ng Stratehiya →',
    'home.cta.title.1': 'Handa Ka Na Bang Maabot ang ',
    'home.cta.title.2': 'Mythical Glory?',
    'home.cta.sub': 'Magsimula sa mga basics at paakyat. Nagsisimula dito ang iyong paglalakbay.',
    'home.cta.begin': 'Simulan ang Paglalakbay →',
    'home.cta.lingo': 'Aralin ang Wika',

    // Home - Quick Nav Cards
    'home.card.gs.title': 'Pagsisimula',
    'home.card.gs.desc': 'Bago ka sa MLBB? Alamin ang mga basics, game modes, controls, at mga beginner tips para magsimula ka nang maayos.',
    'home.card.gs.badge': 'Baguhan',
    'home.card.gm.title': 'Mekanika ng Laro',
    'home.card.gm.desc': 'I-master ang mapa, gold & EXP system, lahat ng 6 na role, emblems, battle spells, at item builds.',
    'home.card.gm.badge': 'Core',
    'home.card.hg.title': 'Gabay sa Bayani',
    'home.card.hg.desc': 'Mag-browse ng 30+ heroes na may role, difficulty, recommended spells, at mahahalagang gameplay tips.',
    'home.card.hg.badge': 'Esensyal',
    'home.card.int.title': 'Intermediate',
    'home.card.int.desc': 'Pahusayin ang farming, map awareness, rotation, at objective control para umakyat sa ranked.',
    'home.card.int.badge': 'Intermediate',
    'home.card.adv.title': 'Advanced',
    'home.card.adv.desc': 'Advanced na macro at micro strategies, counter-jungling, ranked climbing, at mental game.',
    'home.card.adv.badge': 'Advanced',
    'home.card.pro.title': 'Pro Resources',
    'home.card.pro.desc': 'Mga top content creators, opisyal na MPL esports channels, at mga world championship resources.',
    'home.card.pro.badge': 'Pro',

    // Home - Benefits
    'home.benefit.structured.title': 'Nakaayos na Pag-aaral',
    'home.benefit.structured.desc': 'Nakaayos mula sa pinaka-baguhan hanggang sa advanced na mga stratehiya. Sundan ang landas o tumalon sa kailangan mo.',
    'home.benefit.hero.title': 'Tips para sa Bawat Bayani',
    'home.benefit.hero.desc': 'Mga detalyadong gabay para sa 30+ heroes sa lahat ng 6 na role na may difficulty ratings at key combos.',
    'home.benefit.updated.title': 'Palaging Updated',
    'home.benefit.updated.desc': 'Sumasalamin sa kasalukuyang meta strategies at mga pinaka-relevant na content creators sa MLBB community.',

    // Home - Tips
    'home.tip.awareness': 'Palaging tingnan ang minimap kada 3–5 segundo — ang map awareness ang nagpanapanalo.',
    'home.tip.objectives': 'Unahin ang Turtle sa early game (bago mag-4 min) para sa malaking gold advantage.',
    'home.tip.rotation': 'Dapat palaging mag-rotate ang tank mo sa mga lane na na-push para maiwasan ang pagkawala ng turret.',
    'home.tip.farming': 'Ang pag-last-hit ng creeps ay nagbibigay ng mas maraming gold — sikaping i-last-hit lahat sa lane.',

    // Footer
    'footer.tagline': 'Ang kumpletong gabay mo mula Beginner hanggang Mythical Glory. Maging master sa Land of Dawn.',
    'footer.disclaimer': '⚠️ Ito ay fan-made na educational resource. Hindi konektado sa Moonton o Mobile Legends: Bang Bang.',

    // Getting Started
    'gs.tag': '🎮 Baguhan',
    'gs.title.1': 'Pagsisimula ',
    'gs.title.2': 'sa Laro',
    'gs.subtitle': 'Lahat ng kailangan mong malaman para mag-download, mag-setup, at maglaro ng iyong unang mga laban sa Mobile Legends: Bang Bang.',
    'gs.what.title.1': 'Ano ang ',
    'gs.what.title.2': 'Mobile Legends: Bang Bang?',
    'gs.what.p1': 'Ang Mobile Legends: Bang Bang (MLBB) ay isang 5v5 multiplayer online battle arena (MOBA) na laro na ginawa ng Moonton. Inilabas noong 2016, lumaki ito bilang isa sa mga pinakapopular na mobile games sa Southeast Asia at buong mundo, na may milyon-milyong manlalaro araw-araw.',
    'gs.what.p2': 'Dalawang team ng tig-5 manlalaro ang nagpapaligsahan para sirain ang base ng kalaban (ang Nexus). Ang mapa ay may tatlong pangunahing lane — Top, Mid, at Bottom — na konektado ng jungle. Bawat manlalaro ay kumokontrol ng natatanging bayani na may espesyal na kakayahan.',
    'gs.what.p3': 'Ang mga laban ay karaniwang tumatagal ng 15–25 minuto, kaya perpekto ang MLBB para sa mobile gaming.',
    'gs.facts.title': '⚡ Mga Mabilisang Impormasyon',
    'gs.download.title.1': 'Pag-download at ',
    'gs.download.title.2': 'Setup',
    'gs.ui.title.1': 'In-Game ',
    'gs.ui.title.2': 'UI Overview',
    'gs.modes.title.1': 'Mga Game ',
    'gs.modes.title.2': 'Modes',
    'gs.modes.subtitle': 'Nag-aalok ang MLBB ng maraming mode para sa bawat estilo at mood ng paglalaro.',
    'gs.tips.title.1': 'Mga Tips para sa ',
    'gs.tips.title.2': 'Baguhan',
    'gs.mistakes.title.1': 'Mga Karaniwang ',
    'gs.mistakes.title.2': 'Pagkakamali at Solusyon',
    'gs.mistakes.header.mistake': '❌ Karaniwang Pagkakamali',
    'gs.mistakes.header.fix': '✅ Ang Solusyon',
    'gs.quiz.title': '🧠 Pagsusulit sa Kaalaman',

    // Getting Started - Game Modes
    'gs.mode.classic.name': 'Classic',
    'gs.mode.classic.desc': 'Standard na 5v5 match. Pinakamainam para sa pag-practice ng mga heroes at stratehiya nang walang presyon sa rank. Maganda para sa mga baguhan.',
    'gs.mode.ranked.name': 'Ranked',
    'gs.mode.ranked.desc': 'Competitive mode kung saan kumikita ka ng rank points. Maglaro dito kapag naintindihan mo na ang iyong preferred role at ilang heroes.',
    'gs.mode.brawl.name': 'Brawl',
    'gs.mode.brawl.desc': 'Magulo na single-lane random hero mode. Mabilis na mga laban. Maganda para mabilis na maunawaan ang hero abilities.',
    'gs.mode.custom.name': 'Custom',
    'gs.mode.custom.desc': 'Gumawa ng private rooms para mag-practice kasama ang mga kaibigan o specific scenarios. Kapaki-pakinabang para sa pagte-test ng combos.',
    'gs.mode.arcade.name': 'Arcade',
    'gs.mode.arcade.desc': 'Umiikot na masayang mini-game modes. Perpekto para sa pahinga mula sa seryosong laro. Regular na nadadagdagan ng bagong modes.',
    'gs.mode.ai.name': 'vs. AI',
    'gs.mode.ai.desc': 'Lumaban sa mga bot. Ideal kapag bagong natututo ng bagong bayani o nagwa-warm up bago mag-ranked.',

    // Getting Started - Beginner Tips
    'gs.tip.1': 'Magsimula sa mga madaling heroes tulad nina Miya, Freya, o Rafaela.',
    'gs.tip.2': 'Tingnan ang minimap kada ilang segundo — napaka-importante ng map awareness.',
    'gs.tip.3': 'Manatili kasama ng mga ka-team sa early game; iwasang mag-isa sa teritoryo ng kalaban.',
    'gs.tip.4': 'Gamitin ang battle spell (tulad ng Flicker) nang matalino — mahaba ang cooldown nito.',
    'gs.tip.5': 'Huwag ibenta ang mga items para bumili ng iba — i-upgrade sila habang tumatagal ang laro.',
    'gs.tip.6': 'I-mute agad ang mga toxic na manlalaro. Ang mental focus ang nagpanapanalo.',
    'gs.tip.7': 'Basahin ang item descriptions para maunawaan ang binibili mo.',
    'gs.tip.8': 'Maglaro muna ng Classic at vs. AI bago pumasok sa ranked matches.',

    // Getting Started - Mistakes
    'gs.mistake.1.mistake': 'Masyadong pumapasok nang mag-isa',
    'gs.mistake.1.fix': 'Palaging tingnan ang minimap bago sumugod nang malalim sa teritoryo ng kalaban.',
    'gs.mistake.2.mistake': 'Bumibili ng random items',
    'gs.mistake.2.fix': 'Sundin ang recommended builds o gabay para sa role ng iyong bayani.',
    'gs.mistake.3.mistake': 'Hindi pinapansin ang mga objectives',
    'gs.mistake.3.fix': 'Palaging labanan ang Turtle (early game) at Lord (late game).',
    'gs.mistake.4.mistake': 'Hindi nag-ro-rotate',
    'gs.mistake.4.fix': 'Tulungan ang mga ka-team sa ibang lanes kapag safe ang lane mo.',
    'gs.mistake.5.mistake': 'Masyadong matagal sa base',
    'gs.mistake.5.fix': 'Bumalik sa lane o mag-rotate agad pagkatapos gastusin ang gold mo.',

    // Getting Started - Download Steps
    'gs.step.1.title': 'I-download ang App',
    'gs.step.1.desc': 'Hanapin ang "Mobile Legends: Bang Bang" sa App Store (iOS) o Google Play Store (Android). Libre ang download.',
    'gs.step.2.title': 'Gumawa ng Account',
    'gs.step.2.desc': 'Mag-log in gamit ang Facebook, Google, Moonton, o VK. Ang paggamit ng Facebook/Google ay nagkokonekta ng account mo sa iba\'t ibang device.',
    'gs.step.3.title': 'Kumpletuhin ang Tutorial',
    'gs.step.3.desc': 'May built-in tutorial ang MLBB. Kumpletuhin ito nang buo — tinuturo nito ang paggalaw, mga skill, pag-atake, at objectives.',
    'gs.step.4.title': 'I-ayos ang Settings',
    'gs.step.4.desc': 'Pumunta sa Settings → Controls. I-enable ang "Smart Targeting" sa simula. I-adjust ang laki at layout ng skill buttons sa gusto mo.',
    'gs.step.5.title': 'Subukan ang Free Heroes',
    'gs.step.5.desc': 'Nagbibigay ang MLBB ng libreng rotating heroes kada linggo. Subukan sila para matuklasan ang preferred role mo.',
    'gs.step.6.title': 'Maglaro Muna ng vs. AI',
    'gs.step.6.desc': 'Maglaro ng ilang Bot matches bago tumalon sa Classic o Ranked. Maging komportable muna sa bayani mo.',

    // Getting Started - UI Overview
    'gs.ui.minimap.label': 'Minimap',
    'gs.ui.minimap.desc': 'Nagpapakita ng real-time na posisyon ng lahat ng nakikitang heroes. Tingnan ito kada 3–5 segundo.',
    'gs.ui.timer.label': 'Timer at Score',
    'gs.ui.timer.desc': 'Game clock, kill score, at gold advantage display.',
    'gs.ui.gold.label': 'Gold Counter',
    'gs.ui.gold.desc': 'Ang kasalukuyan mong gold. Sinasabi nito kung gaano ka na kalapit sa susunod mong item.',
    'gs.ui.joystick.label': 'Movement Joystick',
    'gs.ui.joystick.desc': 'I-drag para igalaw ang bayani mo. I-tap nang maikli para huminto at auto-attack ang pinakamalapit na kalaban.',
    'gs.ui.skills.label': 'Skill Buttons',
    'gs.ui.skills.desc': 'Ang 3 skills ng bayani mo kasama ang basic attack. Ang Skill 2 ang karaniwang pangunahing ability.',
    'gs.ui.spell.label': 'Battle Spell',
    'gs.ui.spell.desc': 'Espesyal na ability (Flicker, Retribution, atbp.) na pinili bago ang laban.',

    // Getting Started - Quiz
    'gs.quiz.q1': 'Aling game mode ang pinakamainam para sa mga baguhan na walang presyon sa rank?',
    'gs.quiz.q1.a': 'Ranked',
    'gs.quiz.q1.b': 'Classic',
    'gs.quiz.q1.c': 'Brawl',
    'gs.quiz.q1.d': 'vs. AI',
    'gs.quiz.q1.explain': 'Ang Classic mode ang standard na 5v5 match na walang rank stakes — perpekto para sa practice.',
    'gs.quiz.q2': 'Ano ang pinakamahalagang map habit na dapat i-develop bilang baguhan?',
    'gs.quiz.q2.a': 'Palaging nag-pu-push ng turrets',
    'gs.quiz.q2.b': 'Regular na pagtingin sa minimap',
    'gs.quiz.q2.c': 'Pagbili muna ng mamahalin na items',
    'gs.quiz.q2.d': 'Paglaban sa ilalim ng turret ng kalaban',
    'gs.quiz.q2.explain': 'Ang map awareness sa pamamagitan ng minimap ang pinaka-impactful na ugaling buuin sa simula.',
    'gs.quiz.q3': 'Alin sa mga ito ang HINDI standard na role sa MLBB?',
    'gs.quiz.q3.a': 'Marksman',
    'gs.quiz.q3.b': 'Support',
    'gs.quiz.q3.c': 'Healer',
    'gs.quiz.q3.d': 'Assassin',
    'gs.quiz.q3.explain': 'Ang 6 na role ay: Tank, Fighter, Assassin, Mage, Marksman, at Support. Walang dedicated na "Healer" role.',

    // Game Mechanics
    'gm.tag': '⚙️ Core',
    'gm.title.1': 'Mekanika ng ',
    'gm.title.2': 'Laro',
    'gm.subtitle': 'I-master ang mapa, ekonomiya, mga role, emblems, at spells para magkaroon ng matibay na pundasyon sa bawat laban.',
    'gm.map.title.1': 'Ang Mapa: ',
    'gm.map.title.2': 'Land of Dawn',
    'gm.map.desc': 'Ang labanan ay nagaganap sa simetikal na mapa na tinatawag na Land of Dawn. Nahahati ito sa dalawang bahagi — blue side (team mo) at red side (kalaban). Tatlong lane ang nag-uugnay sa mga base, na may jungle sa pagitan.',
    'gm.obj.title': '🎯 Mahahalagang Objectives',
    'gm.gold.title.1': 'Gold at ',
    'gm.gold.title.2': 'EXP System',
    'gm.roles.title.1': 'Mga Role ng ',
    'gm.roles.title.2': 'Bayani',
    'gm.roles.subtitle': 'Ang pag-unawa sa mga role ay pundamental. Kailangan ng bawat team ng balanseng komposisyon para manalo.',
    'gm.emblems.title.1': 'Sistema ng ',
    'gm.emblems.title.2': 'Emblem',
    'gm.emblems.subtitle': 'Ang Emblems ay nagbibigay ng stat bonuses at talent perks. Palaging ilagay ang emblem na naaangkop sa role ng bayani mo.',
    'gm.spells.title.1': 'Mga Battle ',
    'gm.spells.title.2': 'Spells',
    'gm.spells.subtitle': 'Ang Battle Spells ay mga makapangyarihang abilities na pinipili bago ang bawat laban. Kritikal ang tamang pagpili ng spell para sa bayani mo.',
    'gm.items.title.1': 'Items at ',
    'gm.items.title.2': 'Builds',
    'gm.items.subtitle': 'Ang mga items ay binibili gamit ang gold habang naglalaro at malaki ang epekto sa kapangyarihan ng bayani mo.',
    'gm.difficulty': ' Kahirapan',
    'gm.duties': '🎯 Mga Pangunahing Tungkulin',
    'gm.heroes': '🦸 Mga Halimbawang Bayani',
    'gm.spell': '⚡ Inirerekomendang Spell',
    'gm.bestfor': 'Pinakamainam para sa:',

    // Hero Guides
    'hg.tag': '🦸 Mga Bayani',
    'hg.title.1': 'Gabay sa ',
    'hg.title.2': 'Bayani',
    'hg.subtitle': 'Mag-browse ng mga gabay para sa 30 heroes sa lahat ng 6 na role. I-filter ayon sa role para mahanap ang pangunahin mong bayani.',
    'hg.shown': ' ang ipinapakita',
    'hg.hero': ' bayani',
    'hg.heroes': ' bayani',
    'hg.tips': '💡 Mahahalagang Tips',
    'hg.weak': '🔄 Mahina laban sa:',
    'hg.less': '▲ Mas Kaunti',
    'hg.more': '▼ Mga Tips',
    'hg.tier.title.1': 'Kasalukuyang ',
    'hg.tier.title.2': 'Meta Tier List',
    'hg.tier.subtitle': 'Pangkalahatang tier guide para sa ranked play. Nagbabago ang meta sa bawat patch — palaging suriin ang pinakabagong patch notes.',
    'hg.synergy.title.1': 'Synergy at ',
    'hg.synergy.title.2': 'Counter Tips',
    'hg.synergy.strong': '✅ Mga Malakas na Synergy',
    'hg.synergy.counter': '❌ Mga Karaniwang Counter',

    // Intermediate
    'int.tag': '📈 Intermediate',
    'int.title.1': 'Mga Intermediate na ',
    'int.title.2': 'Stratehiya',
    'int.subtitle': 'Tulay mula sa casual player tungo sa consistent na ranked performer gamit ang mga core intermediate concepts na ito.',
    'int.farming.title.1': 'Last Hitting at ',
    'int.farming.title.2': 'Farming',
    'int.farming.desc': 'Ang last hitting ay nangangahulugang ikaw ang nagbigay ng huling hampas sa lane minion para makuha ang buong gold reward. Ang pagkamiss ng last hits — kahit isang atake — ay nangangahulugang nawawalang gold na nagpapalaki habang tumatagal ang laro.',
    'int.farming.stats': '📊 Mga Target sa Farming',
    'int.map.title.1': 'Map Awareness at ',
    'int.map.title.2': 'Minimap',
    'int.rotation.title.1': 'Mga Stratehiya sa ',
    'int.rotation.title.2': 'Rotation',
    'int.obj.title.1': 'Pag-prioritize ng ',
    'int.obj.title.2': 'Objectives',
    'int.comp.title.1': 'Komposisyon ng ',
    'int.comp.title.2': 'Team',
    'int.comp.subtitle': 'Kritikal ang balanseng komposisyon ng team para sa tagumpay. Sa draft/selection screen, bumuo ng team na maraming role ang sakop.',
    'int.engage.title.1': 'Engage vs ',
    'int.engage.title.2': 'Disengage',
    'int.engage.when': '⚔️ Kailan Mag-e-engage',
    'int.disengage.when': '🛡️ Kailan Mag-di-disengage',
    'int.quiz.title': '🧠 Intermediate na Pagsusulit sa Kaalaman',

    // Advanced
    'adv.tag': '🏆 Advanced',
    'adv.title.1': 'Mga Advanced na ',
    'adv.title.2': 'Stratehiya',
    'adv.subtitle': 'Elite-level na macro at micro techniques para sa mga manlalaro na naglalayong maabot ang Mythical Glory at higit pa.',
    'adv.macro.title.1': 'Advanced na ',
    'adv.macro.title.2': 'Macro Play',
    'adv.macro.subtitle': 'Ang Macro ay tumutukoy sa malalaking desisyon sa laro — pagkilos sa mapa, objectives, at pressure.',
    'adv.micro.title.1': 'Advanced na ',
    'adv.micro.title.2': 'Micro Techniques',
    'adv.micro.subtitle': 'Ang Micro ay tumutukoy sa indibidwal na mechanical skill — kung gaano ka ka-precise sa pagkontrol ng bayani mo sa mga laban.',
    'adv.micro.practice': '🎮 Pagsasanay:',
    'adv.cj.title.1': 'Counter ',
    'adv.cj.title.2': 'Jungling',
    'adv.cj.desc': 'Ang counter-jungling ay nangangahulugang pag-invade sa jungle ng kalaban para nakawin ang kanilang camps, tanggihan ang gold/EXP nila, at lumikha ng maagang advantage. High risk, high reward ito.',
    'adv.cj.timers': '⏰ Mahahalagang Jungle Timers',
    'adv.rank.title.1': 'Gabay sa Pag-akyat ',
    'adv.rank.title.2': 'sa Ranked',
    'adv.rank.subtitle': 'Bawat rank tier ay nangangailangan ng iba\'t ibang focus areas. Narito ang pinakamahalaga sa bawat stage.',
    'adv.mental.title.1': 'Mental Game at ',
    'adv.mental.title.2': 'Pamamahala sa Tilt',
    'adv.patch.title.1': 'Meta at ',
    'adv.patch.title.2': 'Patch Analysis',
    'adv.patch.desc': 'Naglalabas ang MLBB ng patches kada 2–4 na linggo. Bawat patch ay maaaring dramatikong baguhin ang meta. Ang pag-adapt sa patches ang nagpapahiwalay sa mga stagnan at umaangat na manlalaro.',

    // Pro Resources
    'pro.tag': '⭐ Pro Level',
    'pro.title.1': 'Mga Pro ',
    'pro.title.2': 'Resources',
    'pro.subtitle': 'Ang mga pinakamahusay na content creators, opisyal na esports channels, at professional resources para pabilisin ang iyong MLBB journey.',
    'pro.creators.title.1': 'Mga Nangungunang Content ',
    'pro.creators.title.2': 'Creators',
    'pro.creators.subtitle': 'Ang mga creators na ito ang nagbibigay ng pinakamagandang educational at entertainment content sa MLBB community.',
    'pro.visit': 'Bisitahin ang Channel →',
    'pro.mpl.title.1': 'Opisyal na MPL ',
    'pro.mpl.title.2': 'Esports Leagues',
    'pro.mpl.subtitle': 'Ang Mobile Legends Professional League (MPL) ang premier competitive circuit. Manood para matuto mula sa mga pinakamahusay na manlalaro sa buong mundo.',
    'pro.mpl.watch': 'Panoorin →',
    'pro.mseries.title.1': 'M-Series ',
    'pro.mseries.title.2': 'World Championship',
    'pro.mseries.desc': 'Ang M-Series ay ang taunang World Championship ng MLBB kung saan nagpapaligsahan ang pinakamagagaling na MPL teams mula sa lahat ng region para sa titulo ng World Champion. Ito ang pinakadakilang tanghalan sa mobile MOBA esports.',
    'pro.mseries.champions': '🏆 Mga Nakaraang Champions',
    'pro.why.title.1': 'Bakit Manood ng ',
    'pro.why.title.2': 'Pro Play?',

    // Patch Notes
    'patch.tag': '📋 Mga Patch Updates',
    'patch.title.1': 'Mga Patch ',
    'patch.title.2': 'Notes',
    'patch.subtitle': 'Manatiling updated sa mga pinakabagong MLBB patches. Alamin kung saan hanapin ang patch notes, paano i-analyze ang mga pagbabago, at i-adapt ang gameplay mo sa bawat update.',
    'patch.where.title.1': 'Saan Hanapin ang ',
    'patch.where.title.2': 'Patch Notes',
    'patch.where.subtitle': 'Maraming sources para manatiling may alam sa bawat MLBB update.',
    'patch.visit': 'Bisitahin ang Source →',
    'patch.analyze.title.1': 'Paano Mag-analyze ng ',
    'patch.analyze.title.2': 'Bagong Patch',
    'patch.analyze.subtitle': 'Sundin ang checklist na ito sa tuwing may bagong patch para manatiling nangunguna sa meta.',
    'patch.terms.title.1': 'Mga Terminolohiya sa ',
    'patch.terms.title.2': 'Patch',
    'patch.terms.subtitle': 'Mga karaniwang termino na makikita mo sa patch notes at kung ano ang ibig sabihin nila.',
    'patch.cycle.title.1': 'MLBB Patch ',
    'patch.cycle.title.2': 'Cycle',
    'patch.cycle.desc': 'Karaniwang naglalabas ang MLBB ng patches kada 2–4 na linggo. Ang malalaking patches ay may kasamang hero adjustments, bagong heroes, item changes, at minsan ay pagbabago sa mapa. Ang pag-unawa sa patch cycle ay tumutulong sa iyo na mag-prepare at mag-adapt nang mas mabilis kaysa sa mga kalaban mo.',
    'patch.cycle.tips.title': '💡 Mga Pro Tips para sa Patch Day',

    // Glossary
    'glossary.tag': '📖 Sanggunian',
    'glossary.title.1': 'MLBB ',
    'glossary.title.2': 'Glossary',
    'glossary.subtitle': 'Isang kumpletong sanggunian ng MLBB terminolohiya, abbreviations, at konsepto. Maghanap ng anumang termino para malaman ang kahulugan nito.',
    'glossary.search.placeholder': 'Maghanap ng mga termino, abbreviations, o paglalarawan...',
    'glossary.total': 'kabuuan',
    'glossary.matching': 'tumutugma sa',
    'glossary.empty': 'Walang nahanap na termino na tumutugma sa',

    // About
    'about.tag': 'ℹ️ Tungkol',
    'about.title.1': 'Tungkol sa ',
    'about.title.2': 'MLBB Academy',
    'about.subtitle': 'Isang fan-made na educational resource na nakatuon sa pagtulong sa mga manlalaro ng lahat ng skill level na ma-master ang Mobile Legends: Bang Bang.',
    'about.mission.title.1': 'Ang Aming ',
    'about.mission.title.2': 'Misyon',
    'about.mission.p1': 'Ginawa ang MLBB Academy para maging pinakacomprehensive, libre, at accessible na learning resource para sa mga manlalaro ng Mobile Legends: Bang Bang sa buong mundo.',
    'about.mission.p2': 'Kahit kakadownload mo pa lang ng laro o nag-pu-push ka na papuntang Mythical Glory, ang site na ito ay nagbibigay ng structured guides, hero-specific tips, at curated pro resources para tulungan kang mag-improve sa bawat yugto ng iyong paglalakbay.',
    'about.mission.p3': 'Naniniwala kami na ang magagandang MLBB resources ay dapat libre, maayos, at tunay na kapaki-pakinabang — walang bayaran, walang kalokohan, puro praktikal na kaalaman na magagamit mo sa susunod mong laban.',
    'about.stats.title': '📊 Pangkalahatang-tingin sa Site',
    'about.disclaimer.title': 'Mahalagang Paalala',
    'about.disclaimer.p1': 'Ang MLBB Academy ay isang fan-made, hindi opisyal na educational resource. Ang website na ito ay hindi kaakibat, hindi inaprubahan, o walang koneksyon sa Moonton o Mobile Legends: Bang Bang sa anumang opisyal na kapasidad.',
    'about.disclaimer.p2': 'Lahat ng game-related content, kabilang ang mga pangalan ng bayani, abilities, items, at game mechanics, ay intellectual property ng Moonton. Ang website na ito ay umiiral para sa layuning pang-edukasyon at komunidad lamang.',
    'about.disclaimer.p3': 'Ang hero data, meta information, at mga stratehiya ay maaaring maging outdated habang regular na nagpa-patch at nag-u-update ang laro. Palaging i-verify ang kasalukuyang meta information sa pinakabagong patch notes.',
    'about.disclaimer.p4': 'Ang mga link sa external content creators at websites ay ibinibigay para sa layuning pang-impormasyon. Hindi kami responsable sa content sa mga external sites.',
    'about.credits.title.1': 'Mga Kredito sa ',
    'about.credits.title.2': 'Komunidad',
    'about.credits.subtitle': 'Ang strategy content ng site na ito ay naimpluwensiyahan ng kamangha-manghang MLBB community at mga dedikadong content creators nito. Espesyal na pasasalamat sa:',
    'about.credits.note': 'Malaki ang naiambag ng mga creators na ito sa MLBB community sa pamamagitan ng educational content, gabay, at entertainment. Bisitahin ang {link} page para mahanap ang kanilang mga channel.',
    'about.credits.link': 'Pro Resources',
    'about.howto.title.1': 'Paano Gamitin ang ',
    'about.howto.title.2': 'Gabay na Ito',
    'about.contribute.title': '🤝 Gusto Mo Bang Mag-ambag?',
    'about.contribute.desc': 'Umuunlad ang MLBB Academy sa kaalaman ng komunidad. Kung mayroon kang mga mungkahi, pagwawasto, o karagdagang ideya sa content:',
    'about.contribute.note': 'Ito ay isang community resource — ang iyong feedback ay nagpapabuti nito para sa lahat.',

    // About - How to Use
    'about.howto.1.title': 'Mga Kumpletong Baguhan',
    'about.howto.1.desc': 'Magsimula sa Getting Started → Game Mechanics → Hero Guides. I-master ang isang bayani bago palawakin ang iyong pool.',
    'about.howto.1.cta': 'Magsimula Dito',
    'about.howto.2.title': 'Casual to Ranked',
    'about.howto.2.desc': 'Basahin ang Intermediate strategies. Mag-focus sa map awareness, farming, at rotation bago mag-push ng ranked.',
    'about.howto.2.cta': 'Level Up',
    'about.howto.3.title': 'Pag-push sa Mythic',
    'about.howto.3.desc': 'Pag-aralan ang Advanced macro/micro, counter-jungling, at mental game section.',
    'about.howto.3.cta': 'Go Advanced',
    'about.howto.4.title': 'Aralin ang Wika',
    'about.howto.4.desc': 'Gamitin ang Glossary anumang oras na makatagpo ka ng hindi pamilyar na termino o abbreviation.',
    'about.howto.4.cta': 'Buksan ang Glossary',

    // About - Stats
    'about.stat.sections': 'Mga Seksyon ng Kurso',
    'about.stat.heroes': 'Gabay sa Bayani',
    'about.stat.glossary': 'Mga Termino sa Glossary',
    'about.stat.creators': 'Mga Featured Creators',
    'about.stat.mpl': 'Mga MPL Region na Sakop',
    'about.stat.cost': 'Halaga ng Paggamit',
    'about.stat.cost.value': 'Libre Magpakailanman',

    // About - Contribute list
    'about.contribute.1': '📧 May nakitang mali? Gusto naming malaman para maayos namin ito.',
    'about.contribute.2': '🦸 Gusto mong magdagdag o palawakin ang isang hero guide? Ipaalam sa amin.',
    'about.contribute.3': '💡 May strategy tip ka na wala dito? Ibahagi ang kaalaman mo.',
    'about.contribute.4': '📹 May kilala kang magaling na creator na dapat naming i-feature? I-recommend sila.',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      return localStorage.getItem('mlbb-lang') || 'en'
    } catch {
      return 'en'
    }
  })

  useEffect(() => {
    try {
      localStorage.setItem('mlbb-lang', language)
    } catch {
      // localStorage not available
    }
  }, [language])

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'tl' : 'en')
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
